steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'ContractBotWebhookDeployFunction'  # Replace with your Cloud Function name
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--entry-point'
      - 'ContractBotWebhookDeployFunction'
      - '--allow-unauthenticated'
